require("core.keymaps")
require("core.packer")
require("core.opts")

require("plugins.nvim-tree")
-- require("plugins.fzf")
require("plugins.telescope")
require("plugins.vim-visual-multi")
require("plugins.monokai")
require("plugins.lualine")
require("plugins.treesitter")
require("plugins.lsp_config")
require("plugins.dap_config")
require("plugins.luasnips_config")
require("plugins.lsp_zero_config")
require("plugins.lint")
require("plugins.nullls")
require("plugins.format")
require("plugins.fidget_config")
require("plugins.blamer")
require("plugins.copilot")
